/**
 * Connexion API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Hello200Response from '../model/Hello200Response';

/**
* Site service.
* @module api/SiteApi
* @version 1.0.0
*/
export default class SiteApi {

    /**
    * Constructs a new SiteApi. 
    * @alias module:api/SiteApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Get info
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Hello200Response} and HTTP response
     */
    getSiteLayoutWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Hello200Response;
      return this.apiClient.callApi(
        '/site/layout', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get info
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Hello200Response}
     */
    getSiteLayout() {
      return this.getSiteLayoutWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
